String.toLocaleString({
	"en-US": {
		"Pending": "Pending",
		"Pantry": "Pantry",
		"Categories": "Categories",
		"Settings": "Settings",
        "General": "General",
        "Language": "Language",
        "Save":"Save",
        "Cancel": "Cancel",
        "English": "English",
        "Portuguese": "Portuguese",
        "products": "products",
        "Product": "Product",
        "Category": "Category",
        "New Category": "New Category",
        "New Product": "New Product",
        "categories": "categories",
        "Name": "Name",
        "Color": "Color",
        "Remove": "Remove",
        "Add": "Add",
        "Edit": "Edit",
        "Done": "Done",
        "Back": "Back",
        "Amount": "Amount",
        "Unit": "Unit",
        "Value": "Price",
        "Uncategorized": "Uncategorized",
        "The entries were updated": "The entries were updated",
        "The entries were saved": "The entries were saved",
        "The entries were added": "The entries were added",
        "The entries were removed": "The entries were removed",
        "Shopping List": "Shopping List",
        "Box": "Box",
        "Piece": "Piece",
        "Package": "Package",
        "Bottle": "Bottle",
        "Sack": "Sack",
        "Dozen": "Dozen",
        "Liter": "Liter",
        "Advanced": "Advanced",
        "Clear All": "Clear All",
        "Import": "Import",
        "Export": "Export",
        "Data": "Data",
        "Reset Settings": "Reset Settings",
        "Are you sure?": "Are you sure?",
        "Warning! This cannot be undone!": "Warning! This cannot be undone!",
        "Currency Symbol": "Currency Symbol",
        "Spanish": "Spanish",
        "About": "About",
	},
	"pt-BR": {
        "Pending": "Pendentes",
		"Pantry": "Despensa",
		"Categories": "Categorias",
		"Settings": "Configurações",
        "General": "Geral",
        "Language": "Idioma",
        "Save": "Salvar",
        "Cancel": "Cancelar",
        "English": "Inglês",
        "Portuguese": "Português",
        "products": "produtos",
        "Product": "Produto",
        "Category": "Categoria",
        "New Category": "Nova Categoria",
        "New Product": "Novo Produto",
        "categories": "categorias",
        "Name": "Nome",
        "Color": "Cor",
        "Remove": "Remover",
        "Add": "Adicionar",
        "Edit": "Editar",
        "Done": "Feito",
        "Back": "Voltar",
        "Amount": "Quantidade",
        "Unit": "Unidade",
        "Value": "Preço",
        "Uncategorized": "Sem Categoria",
        "The entries were updated": "As informações foram atualizadas",
        "The entries were saved": "As informações foram salvas",
        "The entries were added": "As informações foram adicionadas",
        "The entries were removed": "As informações foram removidas",
        "Shopping List": "Lista de Compras",
        "Box": "Caixa",
        "Piece": "Pedaço",
        "Package": "Pacote",
        "Bottle": "Garrafa",
        "Sack": "Saco",
        "Dozen": "Dúzia",
        "Liter": "Litro",
        "Advanced": "Avançado",
        "Clear All": "Limpar Tudo",
        "Import": "Importar",
        "Export": "Exportar",
        "Data": "Dados",
        "Reset Settings": "Redefinir Configurações",
        "Are you sure?": "Você está certo disso?",
        "Warning! This cannot be undone!": "Atenção! Isto não pode ser desfeito!",
        "Currency Symbol": "Moeda",
        "Spanish": "Espanhol",
        "About": "Sobre",
	},
    "pt-ES": {
        "Pending": "Pendiente",
		"Pantry": "Despensa",
		"Categories": "Categorías",
		"Settings": "Ajustes",
        "General": "General",
        "Language": "Idioma",
        "Save": "Salvar",
        "Cancel": "Cancelar",
        "English": "Inglés",
        "Portuguese": "Portugués",
        "products": "productos",
        "Product": "Producto",
        "Category": "Categoría",
        "New Category": "Nueva Categoría",
        "New Product": "Nuevo Producto",
        "categories": "categorías",
        "Name": "Nombre",
        "Color": "Color",
        "Remove": "Retirar",
        "Add": "Añadir",
        "Edit": "Editar",
        "Done": "Hecho",
        "Back": "Retorno",
        "Amount": "Cantidad",
        "Unit": "Unidad",
        "Value": "Precio",
        "Uncategorized": "Sin Categoría",
        "The entries were updated": "Las entradas fueron actualizadas",
        "The entries were saved": "Las entradas se guardaron",
        "The entries were added": "Las entradas fueron agregadas",
        "The entries were removed": "Las entradas se eliminaron",
        "Shopping List": "Lista de Compras",
        "Box": "Caja",
        "Piece": "Pieza",
        "Package": "Paquete",
        "Bottle": "Botella",
        "Sack": "Bolsa",
        "Dozen": "Docena",
        "Liter": "Litro",
        "Advanced": "Avanzado",
        "Clear All": "Quitar todo",
        "Import": "Importación",
        "Export": "Exportación",
        "Data": "Datos",
        "Reset Settings": "Restablecer Ajustes",
        "Are you sure?": "¿Está seguro?",
        "Warning! This cannot be undone!": "¡Atención! Esto no se puede deshacer!",
        "Currency Symbol": "Moneda",
        "Spanish": "Español",
        "About": "Sobre",
	}
});
